name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    name: Build & Upload (${{ matrix.target }})
    needs: create-release
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: x86_64-apple-darwin
            os: macos-13
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-24.04
          - target: x86_64-pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: hsk
          target: ${{ matrix.target }}
          archive: $bin-v$version-$target
          token: ${{ secrets.GITHUB_TOKEN }}
